name: dailysync
services:
  daily-sync:
    build:
      context: ./
      dockerfile: Dockerfile
    image: daily-sync:latest
    container_name: daily-sync
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - CRON_SCHEDULE=*/10 * * * *
      - CRON_COMMAND=cd /app && /usr/local/bin/yarn sync_cn
      - LOG_FILE=/var/log/dailysync.log
    volumes:
      - ./log:/var/log
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
